/**
 * Oblique Strategies data
 * @namespace Oblique
 */

if (!Oblique || typeof Oblique != "object") {
	var Oblique = {};	
}

Oblique.Data = [
	"Abandon \n normal \n instruments",
	"Accept \n advice",
	"Accretion",
	"Allow an \n easement \n (an easement is \n the abandonment of a \n stricture)",
	"Always \n first \n steps",
	"Are there \n sections? \n Consider transitions",
	"Ask people to work \n against \n their better judgement",
	"Ask your \n body",
	"Be dirty",
	"Be extravagant",
	"Be less critical \n more often",
	"Breathe more \n deeply",
	"Change nothing \n and continue with \n immaculate \n consistency",
	"Courage!",
	"Cut a vital \n connection",
	"Decorate, \n decorate",
	"Define an area \n as 'safe' \n and use it as an \n anchor",
	"Destroy -nothing \n -the most \n important \n thing",
	"Discard an \n axiom",
	"Disciplined \n self-indulgence",
	"Disconnect from \n desire",
	"Discover \n the recipes \n you are using and \n abandon them",
	"Distorting time",
	"Do nothing \n for as long as \n possible",
	"Do something \n boring",
	"Do the words need \n changing?",
	"Do we need \n holes?",
	"Don't be afraid of \n things \n because they're \n easy to do",
	"Don't be \n frightened \n of cliches",
	"Don't be \n frightened \n to display your \n talents",
	"Don't break the \n silence",
	"Don't stress \n one thing \n more than another",
	"Emphasise \n differences",
	"Emphasise \n the flaws",
	"Faced with a choice \n do both \n (given by Diter Rot)",
	"Gardening, \n not architecture",
	"Give the \n game away",
	"Give way to \n your worst \n impulse",
	"Go outside. \n Shut the door",
	"Go to an \n extreme, \n move back to a more \n comfortable place",
	"Honour thy error \n as a hidden \n intention",
	"How would you have \n done it?",
	"Humanise \n something \n free of error",
	"In total darkness \n or in a very large room, \n very quietly",
	"Is it \n finished?",
	"Is there something \n missing?",
	"Just \n carry on",
	"Listen to the \n quiet voice",
	"Look at the order \n in which you do \n things",
	"Look closely at the most \n embarrassing \n details and amplify them",
	"Make a blank \n valuable \n by putting it in an \n exquisite frame",
	"Make a sudden, \n destructive \n unpredictable action;\n  incorporate",
	"Make an exhaustive list of \n everything \n you might do and do the \n last thing \n on the list",
	"Make it more \n sensual",
	"Make something \n implied \n more definite \n (reinforce, duplicate)",
	"Not building \n a wall but making \n a brick",
	"Once the search is \n in progress, \n something will be \n found",
	"Only a part, \n not the whole",
	"Only one \n element of each \n kind",
	"Overtly resist \n change",
	"Question \n the heroic \n approach",
	"Remember \n .those quiet \n evenings",
	"Remove ambiguities \n and convert to \n specifics",
	"Remove specifics \n and convert to \n ambiguities",
	"Repetition \n is a form of \n change",
	"Retrace \n your steps",
	"Reverse",
	"Short circuit \n (example; a man eating peas \n with the idea \n that they will improve his virility \n shovels them \n straight \n into his lap)",
	"Simple subtraction",
	"Simply \n a matter of \n work",
	"Slow preparation.. \n Fast execution",
	"State the \n problem in words as \n clearly \n as possible",
	"Take a \n break",
	"Take away \n the elements \n in order of \n apparent \n non importance",
	"The inconsistency \n principle",
	"The most \n important \n thing is the thing \n most easily \n forgotten",
	"Think -inside the work \n -outside the work",
	"Tidy up",
	"Towards the \n insignificant",
	"Trust \n in the you \n of now",
	"Try faking it! \n (given by Stewart Brand)",
	"Turn it \n upside down",
	"Use 'unqualified' \n people",
	"Use an old \n idea",
	"Use an \n unacceptable \n colour",
	"Use filters",
	"Voice nagging \n suspicions",
	"Water",
	"What are you \n really \n thinking about \n just now? \n Incorporate",
	"What mistakes \n did you make \n last time?",
	"What to \n increase? \n What to \n reduce?",
	"What to \n maintain?",
	"What would \n your closest \n friend  \ndo?",
	"What wouldn't \n you do?",
	"When is it \n for?",
	"Where's the \n edge? \n Where does the \n frame start?",
	"Which elements \n can be \n grouped?",
	"Which frame \n would make this \n look right?",
	"Who should be doing \n this job? \n How would they \n do it?",
	"Work at a \n different \n speed",
	"Would anybody \n want it?",
	"You are an \n engineer",
	"You don't \n have to be \n ashamed \n of using your \n own ideas"
];
